### ISSUE TITLE
[dev.icinga.com #10267] Failed to import IDO schema on CentOS7 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icinga2-ansible#37]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10267

**Created by kmf on 2015-10-02 12:34:52 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-01-08 08:24:55 +00:00 (in Redmine)_

---

**Comment by aflatto** [comment]
I just encountered this issue on Centos  7 
TASK [icinga2-ansible-web-ui : Import IDO Schema on Icinga Database (only once)] ***
fatal: [54.187.56.126]: FAILED! => {"changed": false, "failed": true, "msg": "target /usr/share/doc/icinga2-ido-mysql-2.0.2/schema/mysql.sql does not exist on the host"}

**Comment by aflatto** [comment]
I have tested the loading of the scheme on the latest centos, and  the issue has not occurred in 6 fresh attempts.
Closing issue
