### ISSUE TITLE
Installing Icinga2 on Centos 6 fails.                     

### ISSUE THREAD

**Issue by IshwarKanse** [Icinga/icinga2-ansible#5]
TASK: icinga2-ansible-no-ui | Install Icinga2 on RedHat OS \
\ family

failed: [10.0.18.11] => (item={'package': 'nagios-plugins-all'}) => {"changed": false, "failed": true, "item": {"package": "nagios-plugins-all"}, "rc": 0, "results": []}
msg: No Package matching 'nagios-plugins-all' found available, installed or updated

**Comment by dnsmichi** [comment]
Please create an issue over here: https://dev.icinga.org/projects/icinga2-ansible
We don't use github issues.
